# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-26 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180926_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='bkc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(max_length=100)),
                ('eb', models.CharField(max_length=200)),
                ('sub', models.CharField(default='', max_length=100)),
                ('patchlist', models.CharField(max_length=15000)),
                ('task', models.CharField(default='', max_length=100)),
                ('project', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('patch', models.CharField(max_length=1000)),
                ('patchtime', models.DateTimeField()),
                ('owner', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('track', models.CharField(max_length=500)),
                ('available', models.NullBooleanField(default=True)),
                ('category', models.CharField(choices=[('cold boot opt', 'cold boot opt'), ('s2r', 's2r'), ('graphics', 'graphics'), ('wifi', 'wifi'), ('debug only', 'debug only'), ('others', 'others')], default='', max_length=15)),
                ('comments', models.CharField(default='', max_length=200)),
                ('project', models.CharField(max_length=100)),
            ],
        ),
    ]
