# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-26 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_bkc_patch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bkc_acrn_gfx',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bkc_camp',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bkc_evs',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bkc_m',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bkc_o',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bkc_p',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bkc_p_acrn',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bkc_p_camp',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bxtp_acrn_gfx',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bxtp_camp',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bxtp_m',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bxtp_o',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bxtp_p',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bxtp_p_acrn',
            name='project',
        ),
        migrations.RemoveField(
            model_name='bxtp_p_camp',
            name='project',
        ),
    ]
