# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-26 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20180926_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkc_acrn_gfx',
            name='project',
            field=models.CharField(default='acrn_gfx', max_length=100),
        ),
        migrations.AddField(
            model_name='bkc_camp',
            name='project',
            field=models.CharField(default='camp', max_length=100),
        ),
        migrations.AddField(
            model_name='bkc_evs',
            name='project',
            field=models.CharField(default='evs', max_length=100),
        ),
        migrations.AddField(
            model_name='bkc_m',
            name='project',
            field=models.CharField(default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='bkc_o',
            name='project',
            field=models.CharField(default='o', max_length=100),
        ),
        migrations.AddField(
            model_name='bkc_p',
            name='project',
            field=models.CharField(default='p', max_length=100),
        ),
        migrations.AddField(
            model_name='bkc_p_acrn',
            name='project',
            field=models.CharField(default='p_acrn', max_length=100),
        ),
        migrations.AddField(
            model_name='bkc_p_camp',
            name='project',
            field=models.CharField(default='p_camp', max_length=100),
        ),
        migrations.AddField(
            model_name='bxtp_acrn_gfx',
            name='project',
            field=models.CharField(default='acrn_gfx', max_length=100),
        ),
        migrations.AddField(
            model_name='bxtp_camp',
            name='project',
            field=models.CharField(default='camp', max_length=100),
        ),
        migrations.AddField(
            model_name='bxtp_m',
            name='project',
            field=models.CharField(default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='bxtp_o',
            name='project',
            field=models.CharField(default='o', max_length=100),
        ),
        migrations.AddField(
            model_name='bxtp_p',
            name='project',
            field=models.CharField(default='p', max_length=100),
        ),
        migrations.AddField(
            model_name='bxtp_p_acrn',
            name='project',
            field=models.CharField(default='p_acrn', max_length=100),
        ),
        migrations.AddField(
            model_name='bxtp_p_camp',
            name='project',
            field=models.CharField(default='p_camp', max_length=100),
        ),
    ]
