# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-23 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20180926_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bkc_acrn_gfx',
        ),
        migrations.DeleteModel(
            name='bkc_camp',
        ),
        migrations.DeleteModel(
            name='bkc_evs',
        ),
        migrations.DeleteModel(
            name='bkc_m',
        ),
        migrations.DeleteModel(
            name='bkc_o',
        ),
        migrations.DeleteModel(
            name='bkc_p',
        ),
        migrations.DeleteModel(
            name='bkc_p_acrn',
        ),
        migrations.DeleteModel(
            name='bkc_p_camp',
        ),
        migrations.DeleteModel(
            name='bxtp_acrn_gfx',
        ),
        migrations.DeleteModel(
            name='bxtp_camp',
        ),
        migrations.DeleteModel(
            name='bxtp_m',
        ),
        migrations.DeleteModel(
            name='bxtp_o',
        ),
        migrations.DeleteModel(
            name='bxtp_p',
        ),
        migrations.DeleteModel(
            name='bxtp_p_acrn',
        ),
        migrations.DeleteModel(
            name='bxtp_p_camp',
        ),
    ]
