# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mdconfig',
            fields=[
                ('project', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=200)),
                ('distro', models.CharField(max_length=200)),
            ],
        ),
    ]
