# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('build_type', models.IntegerField(choices=[(0, 'engineering'), (1, 'daily'), (2, 'weekly'), (3, 'merge request'), (4, 'candidate'), (5, 'candidate mr1'), (6, 'merge request mr1'), (7, 'weekly mr1'), (8, 'latest'), (9, 'candiate mr0'), (10, 'local')])),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('test_config', models.CharField(blank=True, max_length=8, null=True)),
                ('build', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('builder_name', models.CharField(default='', max_length=30)),
                ('slave_project', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='')),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sn', models.CharField(blank=True, max_length=30, null=True)),
                ('num', models.CharField(blank=True, max_length=30, null=True)),
                ('host_name', models.CharField(blank=True, max_length=30, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('policy', models.IntegerField(choices=[(0, 'public'), (1, 'private')], default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_config', models.CharField(max_length=8)),
                ('available', models.NullBooleanField(default=True)),
                ('pid', models.IntegerField(default=0)),
                ('test_id', models.CharField(default='null', max_length=15)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('favorites', models.ManyToManyField(related_name='task_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Slave')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrendsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.CharField(max_length=30)),
                ('case', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=10)),
                ('build_type', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
            ],
        ),
        migrations.AddField(
            model_name='logger',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Project'),
        ),
        migrations.AddField(
            model_name='logger',
            name='slave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Slave'),
        ),
        migrations.AddField(
            model_name='logger',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Task'),
        ),
        migrations.AddField(
            model_name='logger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildpath',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project'),
        ),
    ]
