# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-01 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slave',
            name='install_status',
            field=models.IntegerField(choices=[(0, 'installing'), (1, 'success'), (2, 'failed')], default=1),
        ),
        migrations.AddField(
            model_name='slave',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
