# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-23 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180801_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slave',
            name='ram',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (8, '8')], default=0),
        ),
    ]
