# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-05 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180823_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildpath',
            name='build_type',
            field=models.IntegerField(choices=[(0, 'engineering'), (1, 'daily'), (2, 'weekly'), (3, 'merge request'), (4, 'candidate'), (5, 'candidate mr1'), (6, 'merge request mr1'), (7, 'weekly mr1'), (8, 'latest'), (9, 'candiate mr0'), (10, 'local'), (11, 'preintegration')]),
        ),
    ]
