# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_configtemplate_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Slave'),
        ),
    ]
