# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20181127_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtemplate',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
